name: kademi_app
description: A sample app for use with kademi
homepage: https://github.com/Kademi/kademi-android-app
issue_tracker: https://github.com/Kademi/kademi-android-app/issues

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  google_fonts: ^0.3.9
  carousel_slider: ^1.4.1
  requests: ^3.1.0
  provider: ^4.0.4
  fluttertoast: ^4.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/test_data/
